require: rubocop-rspec

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 33

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false



AllCops:
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'
    - 'lib/app.rb'