name: "CI"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: builld
        run: |
          bundle
          bundle exec rubocop
          bundle exec rspec --exclude-pattern "spec/e2e/*"
